services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Mindy\Bundle\DataFixtureBundle\:
        resource: '../../*'
        exclude: '../../{Tests}'

    Mindy\Bundle\DataFixtureBundle\DataFixtureManager\Manager:
        public: true
